# Generated by Django 3.0.4 on 2020-03-26 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0002_auto_20200326_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 18, 55, 45, 449142)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 18, 55, 45, 449142)),
        ),
    ]
