# Generated by Django 3.0.4 on 2020-03-26 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0005_auto_20200326_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 20, 9, 23, 700367)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 20, 9, 23, 700367)),
        ),
    ]
