# Generated by Django 3.0.4 on 2020-03-26 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0006_auto_20200326_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 20, 43, 44, 199985)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 20, 43, 44, 199985)),
        ),
    ]
